# Global Flyway configuration
quarkus.flyway.migrate-at-start=true

# DEV (PostgreSQL)
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sav
%dev.quarkus.datasource.username=savuser
%dev.quarkus.datasource.password=savpass
%dev.quarkus.hibernate-orm.database.generation=none

# TEST (H2)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:sav;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.database.generation=none

# PROD (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sav
quarkus.datasource.username=savuser
quarkus.datasource.password=savpass
quarkus.hibernate-orm.database.generation=none

# API Docs
quarkus.swagger-ui.always-include=true

# Logging configuration

## Global default
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

## HTTP Access Log
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %t "%r" %s %b %T

## Application-specific logging
quarkus.log.category."com.entreprise.sav".level=DEBUG

## Hibernate logging
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=false