# Global Flyway configuration
quarkus.flyway.migrate-at-start=true

# DEV (PostgreSQL)
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sav
%dev.quarkus.datasource.username=savuser
%dev.quarkus.datasource.password=savpass
%dev.quarkus.hibernate-orm.database.generation=none

# TEST (H2)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:sav
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.database.generation=none

# PROD (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sav
quarkus.datasource.username=savuser
quarkus.datasource.password=savpass
quarkus.hibernate-orm.database.generation=none

# API Docs
quarkus.swagger-ui.always-include=true
